### ISSUE TITLE
hot insert does not update

### ISSUE THREAD

**Issue by thisconnect** [rauschma/tree-shaking-demo#1]
Hi, first: thanks for your blog post and demos!

I can not get tree-shaking-demo to work properly, I see the messages in the console but no changes in the website.

https://github.com/rauschma/webpack-babel-demo works as expected.

OS X 10.10.5 Node.js 5.3.0, `npm i` gives the following warning:

```
npm WARN EPEERINVALID babel-loader@6.2.0 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN EPEERINVALID webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.
npm WARN EPEERINVALID webpack-dev-server@1.14.0 requires a peer of webpack@>=1.3.0 <3 but none was installed.
npm WARN EPACKAGEJSON tree-shaking-demo No repository field.
```

The only thing I tested was `npm start` and changing 'foo' to 'fooooooo'

(In webpack-babel-demo are no warnings, also seems to work without import 'babel-polyfill')

**Comment by rauschma** [comment]
Thanks for reporting this; I was afraid of that. I hadn’t tested the dev server and left it in for later (it will work eventually). But I now think it’s better to remove the relevant parts, which I just did.
